language: android

jdk: oraclejdk8

env:
  global:
    - ANDROID_API=23
    - ANDROID_BUILD_TOOLS=26.0.2

android:
  components:
    - tools
    - platform-tools
    - build-tools-$ANDROID_BUILD_TOOLS
    - android-$ANDROID_API
